DanySK/Course-DevOps-for-scientific-research

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Upgrade Gradle Wrapper to 6.3

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-2 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-2

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-3 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-3

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-5 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-5

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-6 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-6

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-7 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-7

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-8 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-8

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-9 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-9

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-11 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-11

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-12 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-12

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-13 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-13

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-14 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-14

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-15 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-15

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-16 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-16

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-18 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-18

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-19 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-19

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-17 5.6.1 -> 5.6.4.

Upgrade Gradle Wrapper to 5.6.4 in project-17

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-20 5.6.1 -> 6.3.

Upgrade Gradle Wrapper to 6.3 in project-20

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-20 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-20

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-19 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-19

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-18 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-18

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-17 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-17

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-16 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-16

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-15 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-15

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-14 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-14

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-13 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-13

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-12 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-12

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-11 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-11

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-9 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-9

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-8 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-8

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-7 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-7

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-6 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-6

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-5 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-5

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-3 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-3

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-2 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-2

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-1 6.3 -> 6.4-rc-1.

Upgrade Gradle Wrapper to 6.4-rc-1 in project-1

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-1 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-1

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-2 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-2

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-8 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-8

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-11 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-11

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-12 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-12

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-15 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-15

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-17 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-17

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-18 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-18

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-19 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-19

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-3 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-3

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-7 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-7

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-9 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-9

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-13 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-13

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-14 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-14

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-16 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-16

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-20 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-20

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-5 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-5

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-6 6.4-rc-1 -> 6.4-rc-2.

Upgrade Gradle Wrapper to 6.4-rc-2 in project-6

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-3 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-3

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-2 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-2

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-1 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-1

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-8 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-8

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-7 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-7

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-6 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-6

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-5 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-5

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-9 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-9

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-11 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-11

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-12 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-12

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-20 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-20

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-19 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-19

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-18 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-18

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-17 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-17

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-16 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-16

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-15 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-15

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-14 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-14

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-13 6.4-rc-2 -> 6.4-rc-3.

Upgrade Gradle Wrapper to 6.4-rc-3 in project-13

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-19 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-19

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-18 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-18

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-17 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-17

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-14 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-14

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-1 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-1

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-2 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-2

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-3 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-3

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-5 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-5

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-6 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-6

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-7 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-7

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-8 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-8

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-9 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-9

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-11 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-11

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-12 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-12

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-13 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-13

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-20 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-20

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-15 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-15

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-16 6.4-rc-3 -> 6.4-rc-4.

Upgrade Gradle Wrapper to 6.4-rc-4 in project-16

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-20 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in project-20

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-17 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in project-17

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-15 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in project-15

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-14 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in project-14

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-12 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in project-12

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-11 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in project-11

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in project-9 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in project-9

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.4-rc-4 -> 6.4.

Upgrade Gradle Wrapper to 6.4 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.4-rc-4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.4 -> 6.4.1.

Upgrade Gradle Wrapper to 6.4.1 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.4.1 -> 6.5-rc-1.

Upgrade Gradle Wrapper to 6.5-rc-1 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.5-rc-1 -> 6.5.

Upgrade Gradle Wrapper to 6.5 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.5 -> 6.5.1.

Upgrade Gradle Wrapper to 6.5.1 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.6-rc-2 -> 6.6-rc-3.

Upgrade Gradle Wrapper to 6.6-rc-3 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.6-rc-3 -> 6.6-rc-4.

Upgrade Gradle Wrapper to 6.6-rc-4 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.6-rc-6 -> 6.6.

Upgrade Gradle Wrapper to 6.6 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/15-Test

---

.github/workflows/automerge.yml

This pull request has been created automatically by [Autodelivery](https://github.com/DanySK/autodelivery), at your service.
To the best of this bot's understanding, it updates a content described as
> Automerge on non-CI events
and this PR updates it to the same version of DanySK/centralized-automated-deployer@90f792c.
Hope it helps!

[Autodelivery] update Automerge on non-CI events from DanySK/centralized-automated-deployer@90f792c

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/19-Coverage

---

.github/workflows/build-and-deploy-latex.yml

This pull request has been created automatically by [Autodelivery](https://github.com/DanySK/autodelivery), at your service.
To the best of this bot's understanding, it updates a content described as
> LaTeX build and delivery
and this PR updates it to the same version of DanySK/centralized-automated-deployer@a8c1d64.
Hope it helps!

[Autodelivery] update LaTeX build and delivery from DanySK/centralized-automated-deployer@a8c1d64

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/10-ProjectName

---

.github/workflows/build-and-deploy-latex.yml

This pull request has been created automatically by [Autodelivery](https://github.com/DanySK/autodelivery), at your service.
To the best of this bot's understanding, it updates a content described as
> LaTeX build and delivery
and this PR updates it to the same version of DanySK/centralized-automated-deployer@ad67da0.
Hope it helps!

[Autodelivery] update LaTeX build and delivery from DanySK/centralized-automated-deployer@ad67da0

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.7.1 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/16-Multilang 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.8.1 -> 6.8.2.

Upgrade Gradle Wrapper to 6.8.2 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/20-Checkstyle 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/18-CPP 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/03-BuildAsCode 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/21-Dashboard 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/19-Coverage 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/10-ProjectName 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/02-SimpleTask 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/13-Java 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/11-TaskDescription 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/05-DynamicTasks 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/26-Git 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/08-Plugin 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/15-Test 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/12-Multiproject 6.8.2 -> 6.8.3.

Upgrade Gradle Wrapper to 6.8.3 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/08-Plugin

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/08-Plugin
