03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.5.1 -> 6.6-rc-1.

Upgrade Gradle Wrapper to 6.6-rc-1 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.6-rc-1 -> 6.6-rc-2.

Upgrade Gradle Wrapper to 6.6-rc-2 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.6-rc-4 -> 6.6-rc-5.

Upgrade Gradle Wrapper to 6.6-rc-5 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.6-rc-5 -> 6.6-rc-6.

Upgrade Gradle Wrapper to 6.6-rc-6 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/04-TaskDependencies 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/01-dependencies 6.6 -> 6.6.1.

Upgrade Gradle Wrapper to 6.6.1 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.6.1 -> 6.7.1.

Upgrade Gradle Wrapper to 6.7.1 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.7.1 -> 6.8.

Upgrade Gradle Wrapper to 6.8 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

Gradle wrapper in 03-BuildAutomation/workspace/22-Scans 6.8 -> 6.8.1.

Upgrade Gradle Wrapper to 6.8.1 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/01-dependencies
from 6.8.2 to 7.0.

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/11-TaskDescription

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/12-Multiproject

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/10-ProjectName

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/19-Coverage

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/16-Multilang
from 6.8.1 to 7.0.

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/08-Plugin

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/02-SimpleTask

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/18-CPP

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/13-Java

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/05-DynamicTasks

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/03-BuildAsCode

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/15-Test

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/20-Checkstyle

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/22-Scans

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/21-Dashboard

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/26-Git

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/04-TaskDependencies

Upgrade Gradle Wrapper to 7.0 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/16-Multilang

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/02-SimpleTask

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/18-CPP

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/05-DynamicTasks/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/05-DynamicTasks

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/05-DynamicTasks

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/21-Dashboard

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/21-Dashboard

---

03-BuildAutomation/workspace/10-ProjectName/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/10-ProjectName

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/10-ProjectName

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/15-Test

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/13-Java

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/04-TaskDependencies

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/01-dependencies

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/20-Checkstyle

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/19-Coverage

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/22-Scans

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/11-TaskDescription

Upgrade Gradle Wrapper to 7.0.1 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/16-Multilang/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/16-Multilang

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/16-Multilang

---

03-BuildAutomation/workspace/15-Test/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/15-Test

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/15-Test

---

03-BuildAutomation/workspace/13-Java/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/13-Java

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/13-Java

---

03-BuildAutomation/workspace/04-TaskDependencies/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/04-TaskDependencies

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/04-TaskDependencies

---

03-BuildAutomation/workspace/01-dependencies/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/01-dependencies

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/01-dependencies

---

03-BuildAutomation/workspace/22-Scans/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/22-Scans

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/22-Scans

---

03-BuildAutomation/workspace/08-Plugin/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/08-Plugin

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/08-Plugin

---

03-BuildAutomation/workspace/19-Coverage/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/19-Coverage

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/19-Coverage

---

03-BuildAutomation/workspace/20-Checkstyle/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/20-Checkstyle

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/20-Checkstyle

---

03-BuildAutomation/workspace/11-TaskDescription/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/11-TaskDescription

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/11-TaskDescription

---

03-BuildAutomation/workspace/03-BuildAsCode/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/03-BuildAsCode

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/03-BuildAsCode

---

03-BuildAutomation/workspace/02-SimpleTask/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/02-SimpleTask

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/02-SimpleTask

---

03-BuildAutomation/workspace/26-Git/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/26-Git

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/26-Git

---

03-BuildAutomation/workspace/18-CPP/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/18-CPP

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/18-CPP

---

03-BuildAutomation/workspace/12-Multiproject/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/12-Multiproject

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/12-Multiproject

---

03-BuildAutomation/workspace/21-Dashboard/gradle/wrapper/gradle-wrapper.properties

This pull request upgrades the Gradle wrapper in project  in 03-BuildAutomation/workspace/21-Dashboard

Upgrade Gradle Wrapper to 7.0.2 in 03-BuildAutomation/workspace/21-Dashboard
